# Restricting safe-settings to specific repos.
#
# If no file is specified, the following repositories are excluded by default
# restrictedRepos: ['admin', '.github', 'safe-settings']

# Pattern matching uses glob expressions, e.g use * for wildcards.
# WARN: Looks like 2.1.17 actually uses regexp. Next version should use globs instead!
restrictedRepos:
  exclude:
    - ^.github$
  include:
    - ^infra$
    # - ^workflows$
    - ^md-tasks-notify$
