# This settings file can be used to create org-level settings.

# This is the settings that need to be applied to all repositories in the org.
# See http://docs.github.com/en/rest/repos/repos?apiVersion=2022-11-28#create-an-organization-repository
# for all available settings for a repository.
