# This is the settings that need to be applied to all repositories in the org.

# https://docs.github.com/en/rest/repos/repos?apiVersion=2022-11-28#update-a-repository
repository:

  security:
    # Dependabot alerts.
    enableVulnerabilityAlerts: true
    # Dependabot security updates.
    enableAutomatedSecurityFixes: true

  # private: true

  security_and_analysis:
    advanced_security:
      status: enabled
    code_security:
      status: enabled
    secret_scanning:
      status: enabled
    secret_scanning_push_protection:
      status: enabled
    secret_scanning_ai_detection:
      status: enabled
    secret_scanning_non_provider_patterns:
      status: enabled

  has_issues: true
  has_projects: false
  has_wiki: false

  # is_template: false

  # default_branch: main

  allow_squash_merge: true
  allow_merge_commit: false
  allow_rebase_merge: false
  # allow_auto_merge: false
  delete_branch_on_merge: true
  # allow_update_branch: false

  squash_merge_commit_title: PR_TITLE
  squash_merge_commit_message: PR_BODY
  # merge_commit_title: MERGE_MESSAGE
  # merge_commit_message: BLANK

  # archived: false

  # allow_forking: false

  # web_commit_signoff_required: false
